---
title: "Streptococcus pneumoniae data analysis"
author: "Jan Paul van Meenen"
date: "`r Sys.Date()`"
output: html_document
---

#Packages
```{r}
source("requirements/packages.R")
```

#Functions
```{r}
function_files <- list.files(path = "requirements/functions", pattern = "\\.R$",full.names = TRUE)

for (function_file in function_files) {
  source(function_file)
}
```


#Data Protein panel
##loading
```{r}
data_proteinpanel <- rbind(
    read_xlsx("data/20231124 Pneumococcal protein panel (with accession number)_SH_WM_FV.xlsx", range = "B3:M31"),
    read_xlsx("data/20231124 Pneumococcal protein panel (with accession number)_SH_WM_FV.xlsx", range = "N3:Y30")
    ) %>%
  mutate(
    "Protein class" = case_when(
      `No.` < 24 ~ "Lipoproteins",
      `No.` >= 24 & `No.` < 28 ~ "Cytoplasmic P.",
      `No.` == 28 ~ "Membrane associated P.",
      `No.` >= 29 & `No.` < 38 ~ "Choline-binding P.", 
      `No.` >= 38 & `No.` < 46 ~ "Sortase-anchored P.",
      `No.` == 46 ~ "NCSP",
      TRUE ~ "Others"),
    "Proteins (TIGR4)" = na_if(`Proteins (TIGR4)`, "-"),
    "Proteins (D39)" = na_if(`Proteins (D39)`, "-")
  )

data_proteinpanel
```

## Create fasta    
```{r}
fasta_content <- apply(data_proteinpanel, 1, function(row) {
  paste0(">", row["Proteins (TIGR4)"]," ", row["Protein class"], "\n", row["AA sequence of recombinant protein"])
})

writeLines(fasta_content, "data/fasta/sp_recombinant_protein_sequences.fasta")
```

```{r}
cat(fasta_content)
```

#Data structural
##loading
```{r}
data_structural <- read_xlsx("data/Pneumoproteins_PDB_structuralData.xlsx") %>%
  rename_at(vars(3, 4), ~ c("Proteins (TIGR4) name", "Proteins (TIGR4)")) %>%
  mutate(
    "Protein class" = case_when(
      `No.` < 24 ~ "Lipoproteins",
      `No.` >= 24 & `No.` < 33 ~ "CPBs", 
      `No.` >= 33 & `No.` < 41 ~ "Sortase-anchored P.",
      `No.` >= 41 & `No.` < 45 ~ "Cytoplasmic P.",
      `No.` == 45 ~ "Membrane associated P.",
      `No.` == 46 ~ "NCSP",
      TRUE ~ "Others"),
    "Proteins (TIGR4)" = na_if(`Proteins (TIGR4)`, "-"),
    "Proteins (D39)" = na_if(`Proteins (D39)`, "-")
  )

data_structural  
```



## download all pdb's
```{r}
pdb_download_list <- data_structural %>%
  pull(`PDB entry`) %>%
  na.omit() %>%
  str_split(", ") %>%
  unlist()

pdb_download_list
```

```{r}
pdbs_path = "data/pdb/"
get.pdb(ids = pdb_download_list, path = pdbs_path, overwrite = TRUE)
```

## check missing pdb's and retry
```{r}
pdb_downloads <- list.files(pdbs_path, pattern = "\\.pdb$") %>% sub("\\.pdb$", "", .)

pdb_missing <- setdiff(pdb_download_list, pdb_downloads)
pdb_missing

for (pdb_entry in pdb_missing) {
  print(pdb_entry)
  tryCatch({
    pdb_object <- read.pdb.custom(pdb_entry, rm.alt = FALSE)
    write.pdb(pdb = pdb_object, file = paste0(pdbs_path, pdb_entry, ".pdb"))
  }, error = function(e) {
    print(paste("Error reading PDB file:", pdb_entry, "- Skipping."))
  })
}

pdb_downloads <- list.files(pdbs_path, pattern = "\\.pdb$") %>% sub("\\.pdb$", "", .)

pdb_missing <- setdiff(pdb_download_list, pdb_downloads)
pdb_missing
```
#Convert pdb to fasta
```{r}
fasta_content_list <- c() 

for(pdb_entry in pdb_downloads) {
  print(pdb_entry)
  
  pdb_object <- read.pdb.custom(pdb_entry = pdb_entry, pdb_path = pdbs_path)
  
  if (is.null(pdb_object)) {
    message("Skipping ", pdb_entry, " due to failed PDB retrieval.")
    next
  }
  
  if (exists("seqres", where = pdb_object)) {
    # If seqres exists, use the fasta sequence extraction process
    fasta_sequence <- pdb_object$seqres %>%
      enframe(name = "chain", value = "resid") %>%
      add_count(chain, name = "chain_length") %>%
      group_by(chain) %>%
      mutate(resid = aa321(resid),
             position = row_number()) %>%
      filter(resid %in% names(AMINO_ACID_CODE)[1:20]) %>%
      arrange(desc(chain_length), chain) %>%
      filter(chain_length == max(chain_length)) %>%
      filter(chain == min(chain)) %>%  # In case of tie, choose lowest alphabetically
      pull(resid) %>%
      str_c(collapse = "")
  } else {
    print("no seqres in pdb, will take sequence from atom")
    # If seqres does not exist, use atom data
    fasta_sequence <- pdb_object$atom %>%
      filter(type == "ATOM",
             elety == "CA",
             alt %in% c(NA, "A"),
             resid %in% toupper(AMINO_ACID_CODE)[1:20]) %>%
      add_count(chain, name = "chain_length") %>%
      arrange(desc(chain_length), chain) %>%  # Sort by length (descending), then alphabetically
      filter(chain_length == max(chain_length)) %>%
      filter(chain == min(chain)) %>%
      pull(resid) %>%
      str_c(collapse = "")
  }
  
  fasta_content <- paste0(">", pdb_entry, "\n", fasta_sequence)
  
  fasta_content_list <- c(fasta_content_list, fasta_content) 
  
}

fasta_content_list %>% 
  writeLines("data/fasta/pdb_protein_sequences.fasta")
```

## check for missing fasta's
```{r}
missing_fasta <- setdiff(pdb_downloads,
                        gsub("^>|\n.*", "", fasta_content_list))

missing_fasta
```

# Data structural long format with title 
```{r}
data_structural_long <- data_structural %>%
  separate_rows(`PDB entry`, sep = ", ") %>%
  mutate(PDB = `PDB entry`) %>%
  select(-`PDB entry`)

pdb_titles <- c()

for (pdb_entry in data_structural_long$PDB) {
  print(pdb_entry)
  pdb_file <- paste0(pdbs_path, pdb_entry, ".pdb")
  
  if (file.exists(pdb_file)) {
    pdb_lines <- readLines(pdb_file)
    
    # Extract lines starting with "TITLE"
    title_lines <- grep("^TITLE", pdb_lines, value = TRUE)
    
    # Remove "TITLE" from each line and trim whitespace
    clean_title_lines <- str_trim(gsub("^TITLE\\s+\\d*\\s*", "", title_lines))
    
    # Concatenate into a single string
    pdb_title <- paste(clean_title_lines, collapse = " ")
    print(pdb_title)
  } else {
    print("pdb doesn't exist")
    pdb_title <- NA  # Handle missing files
  }
  
  pdb_titles <- c(pdb_titles, pdb_title)
}

# Add the pdb_title column to the dataframe
data_structural_long$pdb_title <- pdb_titles

write.csv(data_structural_long,
          "data/Pneumoproteins_PDB_structuralData_long.csv", 
          row.names=FALSE)
```
