---
title: "Streptococcus pneumoniae data analysis"
author: "Jan Paul van Meenen"
date: "`r Sys.Date()`"
output: html_document
---

#Packages
```{r}
data_management_packages_to_install <- c("data.table", "tidyverse" ,"readxl","purrr","readr","scales","msa")
data_visualisation_packages_to_install <- c("ggplot2","cowplot","pheatmap","viridisLite","ggseqlogo")
structural_packages_to_install <- c("bio3d","NGLVieweR", "htmlwidgets","htmltools")

packages_to_install <- c(data_management_packages_to_install, 
                         data_visualisation_packages_to_install,
                         structural_packages_to_install)

# Check and install packages using a for loop
for (package in packages_to_install) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
  library(package, character.only = TRUE)
}

BiocManager_packages_to_install <- c("Biostrings","pwalign")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

for (package in BiocManager_packages_to_install) {
  if (!requireNamespace(package, quietly = TRUE)) {
    BiocManager::install(package)
  }
  library(package, character.only = TRUE)
}
```

#Functions
```{r}
source("functions/mrp_pc_functions.R")
```


#Data Protein panel
##loading
```{r}
data_proteinpanel <- rbind(
    read_xlsx("data/20231124 Pneumococcal protein panel (with accession number)_SH_WM_FV.xlsx", range = "B3:M31"),
    read_xlsx("data/20231124 Pneumococcal protein panel (with accession number)_SH_WM_FV.xlsx", range = "N3:Y30")
    ) %>%
  mutate(
    "Protein class" = case_when(
      `No.` < 24 ~ "Lipoproteins",
      `No.` >= 24 & `No.` < 28 ~ "Cytoplasmic P.",
      `No.` == 28 ~ "Membrane associated P.",
      `No.` >= 29 & `No.` < 38 ~ "Choline-binding P.", 
      `No.` >= 38 & `No.` < 46 ~ "Sortase-anchored P.",
      `No.` == 46 ~ "NCSP",
      TRUE ~ "Others"),
    "Proteins (TIGR4)" = na_if(`Proteins (TIGR4)`, "-"),
    "Proteins (D39)" = na_if(`Proteins (D39)`, "-")
  )

data_proteinpanel
```

```{r}
colnames(data_proteinpanel)
```


```{r}
data_proteinpanel %>%
  select("Proteins (TIGR4)","AA sequence of recombinant protein")
```

# Create fasta    
```{r}
fasta_content <- apply(data_proteinpanel, 1, function(row) {
  paste0(">", row["Proteins (TIGR4)"]," ", row["Protein class"], "\n", row["AA sequence of recombinant protein"])
})

writeLines(fasta_content, "data/fasta/sp_recombinant_protein_sequences.fasta")
```

```{r}
cat(fasta_content)
```

#Data structure
##loading
```{r}
data_structural <- read_xlsx("data/Pneumoproteins_PDB_structuralData.xlsx") %>%
  rename_at(vars(3, 4), ~ c("Proteins (TIGR4) name", "Proteins (TIGR4)")) %>%
  mutate(
    "Protein class" = case_when(
      `No.` < 24 ~ "Lipoproteins",
      `No.` >= 24 & `No.` < 33 ~ "CPBs", 
      `No.` >= 33 & `No.` < 41 ~ "Sortase-anchored P.",
      `No.` >= 41 & `No.` < 45 ~ "Cytoplasmic P.",
      `No.` == 45 ~ "Membrane associated P.",
      `No.` == 46 ~ "NCSP",
      TRUE ~ "Others"),
    "Proteins (TIGR4)" = na_if(`Proteins (TIGR4)`, "-"),
    "Proteins (D39)" = na_if(`Proteins (D39)`, "-")
  )

data_structural  
```


## download all pdb's
```{r}
data_structural_with_pdb <- data_structural %>%
  mutate(pdb_objects = map(
    `PDB entry`,  # Column containing PDB entry IDs or file names
    ~ if (!is.na(.x)) {
      # Split the PDB entries if multiple IDs are present
      pdb_list <- strsplit(.x, ",\\s*")[[1]]
      
      # Map over each PDB entry to read the corresponding PDB file
      setNames(
        map(pdb_list, function(pdb_entry) {
          tryCatch(
            {
              # Read the PDB file using read.pdb
              pdb_obj <- read.pdb(pdb_entry)
              pdb_obj$pdb_entry <- pdb_entry
              
              write.pdb(pdb_obj, file = paste0("output/pdb/",pdb_entry, ".pdb"))
              
              return(pdb_obj)
            },
            error = function(e) {
              message(paste("Error reading PDB file:", pdb_entry))  # Optionally print a message on error
              return(NA)  # Return NA if an error occurs
            }
          )
        }),
        pdb_list  # Set the names of the list elements to be the PDB IDs
      )
    } else {
      NA  # For rows where `PDB entry` is NA, return NA
    }
    
    
  )) 
  
```


```{r}
data_structural_with_pdb %>%
  filter(!is.na(`PDB entry`)#,
         #`Protein class` != "Others"
         ) %>%
  pull(pdb_objects) %>%
  map(~ {
    map(.x, function(pdb_object) {
      # Check if pdb_object is a list and contains the necessary components
      if (is.list(pdb_object) && !is.null(pdb_object$pdb_entry) && !is.null(pdb_object$seqres)) {
        # Extract sequence information
        fasta_header <- pdb_object$pdb_entry
        fasta_sequence <- paste(aa321(pdb_object$seqres), collapse = "")
        
        # If both header and sequence are non-empty, return FASTA formatted string
        if (nchar(fasta_header) > 0 && nchar(fasta_sequence) > 0) {
          paste0(">", fasta_header, "\n", fasta_sequence)
        } else {
          # Print a message if either header or sequence is missing
          message("Skipping empty PDB entry: ", pdb_object$pdb_entry)
          return(NULL)  # Skip this entry
        }
      } else {
        return(NULL)  # Return NA if invalid
      }
    })
  }) %>%
  unlist() %>%
  writeLines("data/fasta/pdb_protein_sequences.fasta")
```